name: Create S3 Bucket

on:
  push:
    branches:
      - main    # Set to your main branch, or change as needed
  workflow_dispatch:  # Allows manual runs too

jobs:
  create-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create S3 bucket
      run: |
        aws s3api create-bucket \
          --bucket "mmv6158-gitlab" \
          --region "us-east-1" \
          --create-bucket-configuration LocationConstraint="us-east-1"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
