name: Delete S3 Buckets

on:
  workflow_dispatch:
    inputs:
      bucket_names:
        description: 'Comma-separated list of S3 Bucket Names to delete'
        required: true
        type: string
      region:
        description: 'AWS Region (e.g., us-east-1)'
        required: true
        type: string

jobs:
  delete-buckets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

    - name: Delete all listed S3 buckets
      run: |
        IFS=',' read -ra BUCKETS <<< "${{ github.event.inputs.bucket_names }}"
        for BUCKET in "${BUCKETS[@]}"; do
          BUCKET_TRIMMED=$(echo "$BUCKET" | xargs)
          echo "Emptying $BUCKET_TRIMMED ..."
          aws s3 rm "s3://$BUCKET_TRIMMED" --recursive --region "${{ github.event.inputs.region }}"
          echo "Deleting $BUCKET_TRIMMED ..."
          aws s3api delete-bucket --bucket "$BUCKET_TRIMMED" --region "${{ github.event.inputs.region }}"
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ github.event.inputs.region }}
