name: Delete S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'S3 Bucket Name to delete'
        required: true
        type: string
      region:
        description: 'AWS Region (e.g., us-east-1)'
        required: true
        type: string

jobs:
  delete-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

    - name: Empty S3 bucket
      run: |
        aws s3 rm s3://${{ github.event.inputs.bucket_name }} --recursive --region "${{ github.event.inputs.region }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ github.event.inputs.region }}

    - name: Delete S3 bucket
      run: |
        aws s3api delete-bucket \
          --bucket "${{ github.event.inputs.bucket_name }}" \
          --region "${{ github.event.inputs.region }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ github.event.inputs.region }}
